//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LC_Msg
    {
        public string MsgID { get; set; }
        public string MsgContent { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Status { get; set; }
    }
}
