//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LC_User
    {
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserLevel { get; set; }
        public string Dept { get; set; }
        public string Status { get; set; }
    }
}
